Ka 7
IPLATFORM-TECH/keycloak-admin-1 pull request #10
Opened 2022-07-17 18:15 UTC by GolDiBorh

2022-07-17 21:03 UTC, Aar1s approved these changes

2022-07-18 12:11 UTC, a-s-eliseev requested changes

2022-07-18 12:11 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/entity/Realm.java
> +public class Realm extends BaseEntity {
этот класс уже в мастере

2022-07-18 15:27 UTC, a-s-eliseev approved these changes

2022-07-18 15:27 UTC, merged