KA-34 add Liquibase dependency
IPLATFORM-TECH/keycloak-admin-1 pull request #14
Opened 2022-07-18 18:39 UTC by VahitovRashid

2022-07-19 07:41 UTC, a-s-eliseev requested changes
А этого разве достаточно? Нужны же креды и урла для ликвы

2022-07-19 09:37 UTC, Vladimir1Molchanov approved these changes

2022-07-21 14:35 UTC, a-s-eliseev approved these changes

2022-07-21 14:35 UTC, a-s-eliseev commented on src/main/resources/application.yml
> +    enabled: true
тут конечно вопрос

2022-07-23 16:10 UTC, a-s-eliseev approved these changes

2022-07-23 16:10 UTC, merged