create utility class TimeUtils
IPLATFORM-TECH/keycloak-admin-1 pull request #16
Opened 2022-07-19 16:08 UTC by naturemistake666

2022-07-20 12:21 UTC, Aar1s approved these changes

2022-07-21 13:44 UTC, a-s-eliseev requested changes
1. Все методы - static
2. NonNull на передаваемые параметры
3. Тесты

2022-07-23 16:09 UTC, a-s-eliseev requested changes

2022-07-23 16:09 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/commons/TimeUtilsTest.java
> +class TimeUtilsTest {
этот класс должен быть в тестах

2022-07-23 16:09 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/commons/TimeUtilsTest.java
> +        System.out.println("to local data time");
Весь повторяющийся код нужно вынести в отдельный метод, который запускается перед всеми тестами

2022-07-26 09:47 UTC, Aar1s approved these changes

2022-07-28 07:57 UTC, a-s-eliseev approved these changes

2022-07-28 07:58 UTC, merged