add event_entity service
IPLATFORM-TECH/keycloak-admin-1 pull request #22
Opened 2022-07-22 13:19 UTC by naturemistake666

2022-07-23 12:30 UTC, Vasaluk approved these changes

2022-07-23 16:01 UTC, a-s-eliseev requested changes
В целом - отлично! Одно небольшое замечание)

2022-07-23 16:01 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/controller/EventController.java
> +        final List<Event> event = eventService.getByUsernameAndDte(username, TimeUtils.toLong(localDateTimeStart), TimeUtils.toLong(localDateTimeEnd));
Конвертация даты должна быть в сервисе

2022-07-24 16:50 UTC, a-s-eliseev approved these changes

2022-07-25 15:10 UTC, merged