KA-5
IPLATFORM-TECH/keycloak-admin-1 pull request #3
Opened 2022-07-14 17:57 UTC by Vasaluk

2022-07-14 18:09 UTC, a-s-eliseev requested changes

2022-07-14 18:09 UTC, a-s-eliseev commented on src/main/java/space/eliseev/keycloakadmin/entity/Client.java
> +    private String registration_token;
CamelCase

2022-07-15 05:52 UTC, Aar1s approved these changes

2022-07-15 06:35 UTC, a-s-eliseev approved these changes

2022-07-15 06:35 UTC, merged